name: Test reverse dependencies
on:
  pull_request:
  workflow_dispatch:
jobs:
  reverse_dependencies:
    name: Reverse dependency testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: martinfleis/reverse-dependency-testing@main
        with:
            package_name: libpysal
            ignore: fine
            whitelist: >-
                momepy
                cenpy
                esda
                splot
            include: mapclassify
            install: inequality
            fail_on_failure: false
